import { Geist, Geist_Mono, Outfit } from "next/font/google";
import "./globals.css";

// Configure Geist Sans font
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: 'swap',
});

// Configure Geist Mono font
const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
  display: 'swap',
});

// Configure Outfit font
const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],  // Common weights for variety
  variable: '--font-outfit',  // Add variable for CSS custom property
  display: 'swap',  // Ensures text remains visible during font loading
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: '/favicon.ico',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${outfit.variable} font-outfit antialiased`}
      >
        {children}
      </body>
    </html>
  );
}